volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: sickmoqchima/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: sickmoqchima/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    image: sickmoqchima/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend
